### ISSUE TITLE
[IDEA] True containerization

### ISSUE THREAD

**Issue by alxy** [daftspunk/docker-october#1]
Hi,

I have also played a little bit with Docker/docker-compose and jsut wanted to share my configuration files with you, which make use of containerization and use different containers for each service (webserver, database, application). I did use the awesome october bootstrapper, but I think the conecpt should be adaptable.

docker-compose.yaml
```yaml
version: "3.7"
services:
  app:
    build:
      args:
        user: october
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: october
    container_name: october-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - october

  db:
    image: mysql:5.7
    container_name: october-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - october

  nginx:
    image: nginx:alpine
    container_name: october-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - october

networks:
  october:
    driver: bridge

volumes:
  mysql-volume:
```

Dockerfile
```yaml
FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    zip \
    unzip \
    libzip-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd curl xml zip posix

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Set working directory
WORKDIR /var/www

# Use our service user from now on
USER $user
ENV PATH="/home/$user/.composer/vendor/bin:${PATH}"

# Install October bootstrapper
RUN composer global require --prefer-dist offline/oc-bootstrapper --no-interaction
```
